// Order status constants
export const ORDER_STATUS = {
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERY_ATTEMPTED: 'DELIVERY_ATTEMPTED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

// Email template types
export const EMAIL_TEMPLATE_TYPES = {
  ORDER_STATUS: 'ORDER_STATUS',
  DELIVERY_UPDATE: 'DELIVERY_UPDATE',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE'
};

// Notification priorities
export const NOTIFICATION_PRIORITY = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

// Delivery attempt status
export const DELIVERY_ATTEMPT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PARTIAL: 'PARTIAL',
  RESCHEDULED: 'RESCHEDULED'
};